version: 0.1
phases:
  install:
    commands:
      - mvn package
      - aws cloudformation package --template-file template.yaml --s3-bucket awscodepipeline-vikson --output-template-file template-export.yaml
artifacts:
  type: zip
  files:
    - template-export.yaml
